{% set version = "3.1.0" %}

package:
  name: roman-numerals-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/roman-numerals-py/roman_numerals_py-{{ version }}.tar.gz
  sha256: be4bf804f083a4ce001b5eb7e3c0862479d10f94c936f6c4e5f250aa5ff5bd2d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - flit-core >=3.7
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - roman_numerals
  commands:
    - pip check
    - pytest -vv .
  requires:
    - python
    - pip
    - pytest

about:
  home: https://github.com/AA-Turner/roman-numerals
  license: 0BSD OR CC0-1.0
  license_family: BSD
  license_file: LICENCE.rst
  summary: Manipulate well-formed Roman numerals
  description: |
    This project provides utilities manipulating well-formed Roman 
    numerals, in various programming languages. Currently, 
    there are implementations in Python and Rust.
  dev_url: https://github.com/AA-Turner/roman-numerals
  doc_url: https://github.com/AA-Turner/roman-numerals/blob/master/README.rst

extra:
  recipe-maintainers:
    - AA-Turner
